<div id="runner"></div>
<textarea id="note" placeholder="Note" ></textarea>
<a href="" class="button start" id="startTask">Start</a>

<script type="text/javascript">
    $(document).ready(function(){
        var runner = $('#runner');
        var working = <?php echo $running; ?>;
        runner.runner({
            autostart: working,
            startAt: <?php echo $dateDiff; ?>
        });

        var button = $('#startTask');

        buttonStyle(working, button);
        button.click(function(event){
            event.preventDefault();
            var note = $("#note").val();
            if(!working){
                $.ajax({
                    type: 'POST',
                    data: {note: note},
                    url: 'timemanager/start',
                    success: function(data){
                        var r = $.parseJSON(data);
                        console.log("starting task " + r.response);
                        working = true;
                        runner.runner('reset');
                        runner.runner('start');
                        buttonStyle(working, button);
                    }
                });
            }else{
                $.ajax({
                    type: 'POST',
                    url: 'timemanager/stop',
                    success: function(data){
                        var r = $.parseJSON(data);
                        console.log("stopping task " + r.response);
                        working = false;
                        runner.runner('stop');
                        buttonStyle(working, button);
                    }
                });
            }

        });
    });

    function buttonStyle(working, button){
        if(!working){
            $(button).removeClass('working');
            $(button).text('Start');
        }else{
            $(button).addClass('working');
            $(button).text('Stop');
        }
    }
</script>



<?php
var_dump($tasks);
?>