<?php

/**
 * Generated by ZF2ModuleCreator
 */
return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'TimeManager\Controller\TimeManager' =>  'TimeManager\Controller\TimeManagerController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'timemanager' => array(
                'type' => 'segment',
                'options' => array(
                    'route' => '/timemanager[/:action][/:id]',
                    'constraints' => array(
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                    ),
                    'defaults' => array(
                        'controller' => 'TimeManager\Controller\TimeManager',
                        'action' => 'index',
                    )
                )
            )
        ),
    )
);